"""This is a setup.py script generated by py2applet. Only needed for the py2app call in MacOS.

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["src/main.py"]
DATA_FILES = [
  "src/ui/",
  "src/utils_bpy/",
  "src/utils_common/",
  "src/utils_rr/",
]
OPTIONS = {"iconfile": "src/icon/icon.ico"}

setup(
  app=APP,
  data_files=DATA_FILES,
  options={"py2app": OPTIONS},
  setup_requires=["py2app"],
)
