# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\x10render_rob_state\"\x90\x01\n\x10preview_settings\x12\x0f\n\x07samples\x18\x01 \x01(\x05\x12\x13\n\x0bsamples_use\x18\x02 \x01(\x08\x12\x12\n\nframe_step\x18\x03 \x01(\x05\x12\x16\n\x0e\x66rame_step_use\x18\x04 \x01(\x08\x12\x12\n\nresolution\x18\x05 \x01(\x05\x12\x16\n\x0eresolution_use\x18\x06 \x01(\x08\"\x86\x01\n\x08settings\x12\x14\n\x0c\x62lender_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\x1a\n\x12\x62lender_files_path\x18\x03 \x01(\t\x12\x33\n\x07preview\x18\x04 \x01(\x0b\x32\".render_rob_state.preview_settings\"\xff\x02\n\nrender_job\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x0e\n\x06\x63\x61mera\x18\x03 \x01(\t\x12\r\n\x05start\x18\x04 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x05 \x01(\x05\x12\x0f\n\x07samples\x18\x06 \x01(\x05\x12\x13\n\x0bmotion_blur\x18\x07 \x01(\x08\x12\x13\n\x0bnew_version\x18\x08 \x01(\x08\x12\x14\n\x0chigh_quality\x18\t \x01(\x08\x12\x19\n\x11\x61nimation_denoise\x18\n \x01(\x08\x12\x0f\n\x07\x64\x65noise\x18\x0b \x01(\x08\x12\r\n\x05scene\x18\x0c \x01(\t\x12\x12\n\nview_layer\x18\r \x01(\t\x12\x0f\n\x07\x63omment\x18\x0e \x01(\t\"2\n\x0b\x66ile_format\x12\x07\n\x03PNG\x10\x00\x12\x08\n\x04TIFF\x10\x01\x12\x07\n\x03\x45XR\x10\x02\x12\x07\n\x03JPG\x10\x03\"&\n\rrender_engine\x12\n\n\x06\x43YCLES\x10\x00\x12\t\n\x05\x45\x45VEE\x10\x01\"\x1a\n\x06\x64\x65vice\x12\x07\n\x03GPU\x10\x00\x12\x07\n\x03\x43PU\x10\x01\"l\n\x10render_rob_state\x12,\n\x08settings\x18\x01 \x01(\x0b\x32\x1a.render_rob_state.settings\x12*\n\x04jobs\x18\x02 \x03(\x0b\x32\x1c.render_rob_state.render_jobb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PREVIEW_SETTINGS']._serialized_start=34
  _globals['_PREVIEW_SETTINGS']._serialized_end=178
  _globals['_SETTINGS']._serialized_start=181
  _globals['_SETTINGS']._serialized_end=315
  _globals['_RENDER_JOB']._serialized_start=318
  _globals['_RENDER_JOB']._serialized_end=701
  _globals['_RENDER_JOB_FILE_FORMAT']._serialized_start=583
  _globals['_RENDER_JOB_FILE_FORMAT']._serialized_end=633
  _globals['_RENDER_JOB_RENDER_ENGINE']._serialized_start=635
  _globals['_RENDER_JOB_RENDER_ENGINE']._serialized_end=673
  _globals['_RENDER_JOB_DEVICE']._serialized_start=675
  _globals['_RENDER_JOB_DEVICE']._serialized_end=701
  _globals['_RENDER_ROB_STATE']._serialized_start=703
  _globals['_RENDER_ROB_STATE']._serialized_end=811
# @@protoc_insertion_point(module_scope)
