"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['renderrob.py']
DATA_FILES = ["ui/", "icons/"]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app',
                    'shiboken6',
                    'pylint',
                    'pyside6',
                    'protobuf',
                    'PySide6-Essentials',
                    'PySide6-Addons',
                    'bpy',
                    'nuitka'],
)
