name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt install protobuf-compiler
          sudo apt install libgl1
      - name: Build proto bindings
        run: |
          protoc --proto_path=proto/ --python_out=proto/ proto/state.proto
          protoc --proto_path=proto/ --python_out=proto/ proto/cache.proto
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --extension-pkg-whitelist=PySide6 --indent-string='  ' --disable="R, no-member, import-error, no-name-in-module" --generated-members
      - name: Run unittests
        run: |
          python -m unittest discover -s . -p '*_test.py'
