name: RenderRobBuild

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            path: ~/Library/Caches/pip
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build proto bindings
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v24.0/protoc-24.0-linux-x86_64.zip

          unzip protoc-24.0-linux-x86_64.zip
          sudo cp bin/protoc /usr/local/bin/protoc
          protoc --version
          protoc --proto_path=proto/ --python_out=proto/ proto/state.proto
          protoc --proto_path=proto/ --python_out=proto/ proto/cache.proto
      - name: Build
        run: |
          pyside6-deploy -c .\pysidedeploy.spec
